# Generated by Django 4.0.3 on 2022-05-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpArticle',
        ),
    ]
