# Generated by Django 4.0.3 on 2022-05-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helparticle',
            name='articleNum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
