# Generated by Django 4.0.3 on 2022-09-20 05:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(default='Нет заголовка', max_length=50)),
                ('text', models.TextField(max_length=600)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codenumber', models.CharField(default=0, max_length=6)),
                ('codeWord', models.CharField(default='None', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_page.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_page.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_page.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='codenumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_page.classes'),
        ),
    ]
