# Generated by Django 4.0.3 on 2022-10-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_page', '0003_article_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
